# Dates and Time

In [1]:
import datetime as dt
import time as tm

In [2]:
tm.time()

1542771013.422884

In [4]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2018, 11, 20, 22, 30, 47, 358956)

In [5]:
delta = dt.timedelta(days=100)
dtnow + delta

datetime.datetime(2019, 2, 28, 22, 30, 47, 358956)

In [8]:
dtnow.date()+ delta

datetime.date(2019, 2, 28)

# Numpy

In [2]:
import numpy as np
np.arange(1,200,15)

array([  1,  16,  31,  46,  61,  76,  91, 106, 121, 136, 151, 166, 181,
       196])

In [15]:
np.linspace(1,3,20)

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [20]:
n = np.linspace(1,3,20)
n.resize(4,5)
n

array([[1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263],
       [1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842],
       [2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421],
       [2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ]])

In [23]:
x = np.array(object=[1,2,3])
y = np.array(object=[4,5,6])
x.dot(y)

32

In [37]:
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.stack([x,y]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
x.dtype

dtype('int64')

In [41]:
x.astype('float64')

array([1., 2., 3.])

In [43]:
x.sum(),x.mean(),x.std()

(6, 2.0, 0.816496580927726)

In [45]:
x.argmax(),x.argmin()

(2, 0)

In [47]:
m = np.arange(36)
m.resize(6,6)
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [50]:
m[m>30]=30
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [51]:
m2 = m[:3,:3]

In [54]:
m2[:,:]=0
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
m

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [56]:
m3= m[:3,:3].copy()
m3[:,:] =-1
m

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [57]:
test = np.random.randint(1,4,[5,6])
test

array([[3, 2, 2, 1, 2, 2],
       [2, 2, 3, 3, 2, 2],
       [3, 3, 3, 1, 1, 2],
       [1, 1, 3, 1, 3, 2],
       [2, 2, 1, 2, 2, 1]])

In [58]:
for i in range(len(test)):
    print(test[i])

[3 2 2 1 2 2]
[2 2 3 3 2 2]
[3 3 3 1 1 2]
[1 1 3 1 3 2]
[2 2 1 2 2 1]


In [59]:
for i,row in enumerate(test):
    print(i,row)

0 [3 2 2 1 2 2]
1 [2 2 3 3 2 2]
2 [3 3 3 1 1 2]
3 [1 1 3 1 3 2]
4 [2 2 1 2 2 1]


In [60]:
test2 = np.random.randint(1,4,[5,6])
for i, j in zip(test,test2):
    print("{} + {}".format(i,j))

[3 2 2 1 2 2] + [3 2 2 2 2 3]
[2 2 3 3 2 2] + [1 2 2 2 3 1]
[3 3 3 1 1 2] + [3 2 1 1 2 2]
[1 1 3 1 3 2] + [1 2 1 1 2 2]
[2 2 1 2 2 1] + [3 1 2 3 2 2]


# Pandas

In [13]:
import pandas as pd 
s = pd.Series(data =[1,2,None],index=[1,2,3])

In [16]:
s[3]==np.nan

False

In [18]:
np.isnan(s[3])

True

## Pandas Datetime

In [21]:
pd.Period('2018-11-05 5H')

Period('2018-11-05 05:00', 'H')

In [24]:
pd.Timestamp('1-2-1992 12:21 AM')

Timestamp('1992-01-02 00:21:00')

In [26]:
pd.to_datetime('12-3-2017')

Timestamp('2017-12-03 00:00:00')

In [34]:
pd.date_range(start='2018-12-12',periods=5,freq='W-MON')

DatetimeIndex(['2018-12-17', '2018-12-24', '2018-12-31', '2019-01-07',
               '2019-01-14'],
              dtype='datetime64[ns]', freq='W-MON')